INSERT INTO `pcs_op_log_template` (`id`, `title`, `content`, `link`, `bgroup`) VALUES ('LOG_TEM_PIPELINE_CONFIG_CREATE', '配置创建', '<span style=\"color: #003c7f\">${user}</span>\n<span style=\"padding: 0 5px\">添加了</span>\n<span style=\"display: inline-block;\n    width: 22px; height: 22px;\n    line-height: 22px; border-radius: 4px;\n    text-align: center;\n    color: black;background: #cad2f3;\">${name}</span>\n  <span style=\"color: #003c7f\">${pipelineName}</span>的${message}', '/index/task/${pipelineId}/config', 'matflow');
INSERT INTO `pcs_op_log_template` (`id`, `title`, `content`, `link`, `bgroup`) VALUES ('LOG_TEM_PIPELINE_CONFIG_DELETE', '配置删除', '<span style=\"color: #003c7f\">${user}</span>\n<span>删除了</span>\n<span style=\"display: inline-block;\n    width: 22px; height: 22px;\n    line-height: 22px; border-radius: 4px;\n    text-align: center;\n    color: black;background: #cad2f3;\">${name}</span>\n<span style=\"color: #003c7f\">${pipelineName}</span>的${message}', '/index/task/${pipelineId}/config', 'matflow');
INSERT INTO `pcs_op_log_template` (`id`, `title`, `content`, `link`, `bgroup`) VALUES ('LOG_TEM_PIPELINE_CONFIG_UPDATE', '配置更新', '<span style=\"color: #003c7f\">${user}</span>\n<span style=\"padding: 0 5px\">更新了</span>\n<span style=\"display: inline-block;\n    width: 22px; height: 22px;\n    line-height: 22px; border-radius: 4px;\n    text-align: center;\n    color: black;background: #cad2f3;\">${name}</span>\n<span style=\"color: #003c7f\">${pipelineName}</span>的${message}', '/index/task/${pipelineId}/config', 'matflow');
INSERT INTO `pcs_op_log_template` (`id`, `title`, `content`, `link`, `bgroup`) VALUES ('LOG_TEM_PIPELINE_CREATE', '流水线创建', '<span style=\"color: #003c7f\">${user}</span>\n<span style=\"padding: 0 5px\">创建了流水线</span>\n<span style=\"display: inline-block;\n    width: 22px; height: 22px;\n    line-height: 22px; border-radius: 4px;\n    text-align: center;\n    color: black;background: #cad2f3;\">${name}</span>\n<span style=\"color: #003c7f\">${pipelineName}</span>', '/index/task/${pipelineId}/survey', 'matflow');
INSERT INTO `pcs_op_log_template` (`id`, `title`, `content`, `link`, `bgroup`) VALUES ('LOG_TEM_PIPELINE_DELETE', '流水线删除', '<span  style=\"color: #003c7f\">${user}</span>\n<span  style=\"padding: 0 5px\">删除了流水线</span>\n<span style=\"display: inline-block;\n    width: 22px; height: 22px;\n    line-height: 22px; border-radius: 4px;\n    text-align: center;\n    color: black;background: #cad2f3;\">${name}</span>\n<span style=\"color: #003c7f\">${pipelineName}</span>', '/index/task/${pipelineId}/survey', 'matflow');
INSERT INTO `pcs_op_log_template` (`id`, `title`, `content`, `link`, `bgroup`) VALUES ('LOG_TEM_PIPELINE_EXEC', '流水线执行', '<span style=\"color: \"#003c7f\">${user}</span>\n<span style=\"padding: 0 5px\">执行了流水线</span>\n<span style=\"display: inline-block;\n    width: 22px; height: 22px;\n    line-height: 22px; border-radius: 4px;\n    text-align: center;\n    color: black;background: #cad2f3;\">${name}</span>\n<span style=\"color: \"#003c7f\">${pipelineName}</span>', '/index/task/${pipelineId}/survey', 'matflow');
INSERT INTO `pcs_op_log_template` (`id`, `title`, `content`, `link`, `bgroup`) VALUES ('LOG_TEM_PIPELINE_RUN', '流水线运行', '<span style=\"padding-right:5px\"流水线</span>\n<span style=\"display: inline-block;\n    width: 22px; height: 22px;\n    line-height: 22px; border-radius: 4px;\n    text-align: center;\n    color: black;background: #cad2f3;\">${name}</span>\n<span style=\"color: #003c7f\">${pipelineName}</span>\n<img src=${image} height=25px width=25px>执行${message}', '/index/task/${pipelineId}/structure', 'matflow');
INSERT INTO `pcs_op_log_template` (`id`, `title`, `content`, `link`, `bgroup`) VALUES ('LOG_TEM_PIPELINE_UPDATE', '流水线更新', '<span style=\"color: #003c7f\">${user}</span>\n<span style=\"padding: 0 5px\">更新流水线</span>\n<span style=\"display: inline-block;\n    width: 22px; height: 22px;\n    line-height: 22px; border-radius: 4px;\n    text-align: center;\n    color: black;background: #cad2f3;\">${name}</span>\n<span style=\"color: #003c7f\">${pipelineName}</span>的${message}', '/index/task/${pipelineId}/survey', 'matflow');

INSERT INTO `pcs_op_log_type` (`id`, `name`, `bgroup`) VALUES ('LOG_PIPELINE', '流水线', 'matflow');
INSERT INTO `pcs_op_log_type` (`id`, `name`, `bgroup`) VALUES ('LOG_PIPELINE_AUTH', '权限变更', 'matflow');
INSERT INTO `pcs_op_log_type` (`id`, `name`, `bgroup`) VALUES ('LOG_PIPELINE_CONFIG', '配置', 'matflow');
INSERT INTO `pcs_op_log_type` (`id`, `name`, `bgroup`) VALUES ('LOG_PIPELINE_RUN', '运行', 'matflow');
INSERT INTO `pcs_op_log_type` (`id`, `name`, `bgroup`) VALUES ('LOG_PIPELINE_USER', '成员邀请', 'matflow');






