FROM hahahh
ADD /target/doublekit-pipeline-1.0.0-SNAPSHOT-distribution.tar.gz /usr/local
WORKDIR /usr/local/doublekit-pipeline-1.0.0-SNAPSHOT
EXPOSE 8080
EXPOSE 3306
#ENTRYPOINT ["/usr/sbin/init"]
#CMD ["sh /usr/local/doublekit-pipeline-1.0.0-SNAPSHOT/bin/startup.sh"]
#CMD sh /usr/local/doublekit-pipeline-1.0.0-SNAPSHOT/bin/mysqlstart.sh





