FROM tiklab:1.0.0
ADD /target/tiklab-matflow-1.0.0-SNAPSHOT-distribution.tar.gz /usr/local
WORKDIR /usr/local/tiklab-matflow-1.0.0-SNAPSHOT
EXPOSE 8080
EXPOSE 3306
RUN sh /opt/mysql-8.0.28/start.sh





